### ISSUE TITLE
Wakatime not work at new version

### ISSUE THREAD

**Issue by JJplane** [wakatime/jetbrains-wakatime#149] opened 2020-08-16 11:25 UTC
at the version professional 2020.2, wakatime doesn't work after i enter the api key, save.nothing see on the dashboard. this problem occur on not only my IDE but also my friends'

**Comment by alanhamlett** [comment] 2020-08-16 16:30
I'm not able to reproduce this, also using 2020.2. If you turn on debug mode, are there any error messages in your `~/.wakatime.log` file or `idea.log` file?

Also, which operating system are you and your friends using?

**Comment by hjansen** [comment] 2020-09-09 19:06
I have the same problem under OSX Catalina with RubyMine 2019.2.2

If i enable debug mode i get the following exception:

`
java.lang.NullPointerException
	at com.intellij.ui.messages.SheetMessage.<init>(SheetMessage.java:78)
	at com.intellij.ui.messages.JBMacMessages.showErrorDialog(JBMacMessages.java:189)
	at com.intellij.openapi.ui.Messages.showWarningDialog(Messages.java:891)
	at com.wakatime.intellij.plugin.WakaTime.checkDebug(WakaTime.java:161)
	at com.wakatime.intellij.plugin.WakaTime.initComponent(WakaTime.java:84)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:503)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:126)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$load$7(ApplicationImpl.java:414)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:414)
	at com.intellij.idea.IdeaApplication.lambda$executeInitAppInEdt$5(IdeaApplication.java:150)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:438)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
`

**Comment by JJplane** [comment] 2020-09-10 10:53
> I have the same problem under OSX Catalina with RubyMine 2019.2.2
> 
> If i enable debug mode i get the following exception:
> 
> `java.lang.NullPointerException at com.intellij.ui.messages.SheetMessage.<init>(SheetMessage.java:78) at com.intellij.ui.messages.JBMacMessages.showErrorDialog(JBMacMessages.java:189) at com.intellij.openapi.ui.Messages.showWarningDialog(Messages.java:891) at com.wakatime.intellij.plugin.WakaTime.checkDebug(WakaTime.java:161) at com.wakatime.intellij.plugin.WakaTime.initComponent(WakaTime.java:84) at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:503) at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:126) at com.intellij.openapi.application.impl.ApplicationImpl.lambda$load$7(ApplicationImpl.java:414) at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169) at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591) at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537) at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59) at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156) at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:414) at com.intellij.idea.IdeaApplication.lambda$executeInitAppInEdt$5(IdeaApplication.java:150) at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313) at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776) at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727) at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721) at java.base/java.security.AccessController.doPrivileged(Native Method) at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746) at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:438) at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)`



> I'm not able to reproduce this, also using 2020.2. If you turn on debug mode, are there any error messages in your `~/.wakatime.log` file or `idea.log` file?
> 
> Also, which operating system are you and your friends using?

Now the dashboard shows the activities.When I used wakatime at vscode IDE before, the dashboard showed activities right away.But at pycharm 2020.2 I find it work well until I received a repport by email, which is several days later.We used plug at the Windows 10.Thanks for your reply!

**Comment by HamidRezaAshkiyan** [comment] 2020-10-02 18:23
I had same problem after i have upgraded to 2020.2 it stopped working. and this is my debug information.

> 2020-10-02 21:48:49,723 [ 362725]   WARN -                       WakaTime - Cannot run program "C:\Users\Hamid Reza\AppData\Roaming\WakaTime\wakatime-cli\wakatime-cli.exe": CreateProcess error=2, The system cannot find the file specified 
> java.io.IOException: Cannot run program "C:\Users\Hamid Reza\AppData\Roaming\WakaTime\wakatime-cli\wakatime-cli.exe": CreateProcess error=2, The system cannot find the file specified
> 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
> 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
> 	at java.base/java.lang.Runtime.exec(Runtime.java:592)
> 	at java.base/java.lang.Runtime.exec(Runtime.java:451)
> 	at com.wakatime.intellij.plugin.WakaTime.sendHeartbeat(WakaTime.java:231)
> 	at com.wakatime.intellij.plugin.WakaTime.processHeartbeatQueue(WakaTime.java:223)
> 	at com.wakatime.intellij.plugin.WakaTime.access$100(WakaTime.java:46)
> 	at com.wakatime.intellij.plugin.WakaTime$4.run(WakaTime.java:151)
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
> 	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
> 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 	at java.base/java.lang.Thread.run(Thread.java:834)
> Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
> 	at java.base/java.lang.ProcessImpl.create(Native Method)
> 	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:478)
> 	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:154)
> 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
> 	... 13 more

**Comment by gandarez** [comment] 2020-10-03 11:37
I have WakaTime installed here on macOS Catalina and tested it with Rider 2020.2 with no errors.

**Comment by HamidRezaAshkiyan** [comment] 2020-10-03 12:11
I'm on windows 10 2004. I have uninstalled and installed several times but it didnt work. Is there anyway to add wakatime-cli.exe manually?

**Comment by Hephaest** [comment] 2020-11-24 13:40
> > I have the same problem under OSX Catalina with RubyMine 2019.2.2
> > If i enable debug mode i get the following exception:
> > `java.lang.NullPointerException at com.intellij.ui.messages.SheetMessage.<init>(SheetMessage.java:78) at com.intellij.ui.messages.JBMacMessages.showErrorDialog(JBMacMessages.java:189) at com.intellij.openapi.ui.Messages.showWarningDialog(Messages.java:891) at com.wakatime.intellij.plugin.WakaTime.checkDebug(WakaTime.java:161) at com.wakatime.intellij.plugin.WakaTime.initComponent(WakaTime.java:84) at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:503) at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:126) at com.intellij.openapi.application.impl.ApplicationImpl.lambda$load$7(ApplicationImpl.java:414) at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169) at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591) at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537) at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59) at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156) at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:414) at com.intellij.idea.IdeaApplication.lambda$executeInitAppInEdt$5(IdeaApplication.java:150) at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313) at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776) at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727) at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721) at java.base/java.security.AccessController.doPrivileged(Native Method) at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746) at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:438) at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)`
> 
> > I'm not able to reproduce this, also using 2020.2. If you turn on debug mode, are there any error messages in your `~/.wakatime.log` file or `idea.log` file?
> > Also, which operating system are you and your friends using?
> 
> Now the dashboard shows the activities.When I used wakatime at vscode IDE before, the dashboard showed activities right away.But at pycharm 2020.2 I find it work well until I received a repport by email, which is several days later.We used plug at the Windows 10.Thanks for your reply!

The same as JJplane! I am a WakaTime beginner, really need this work efficient in Pycharm.

**Comment by HealUP** [comment] 2023-03-10 17:07
i have a same problem with 14.1.4 version 
how to solve??? thanks

> I had same problem after i have upgraded to 2020.2 it stopped working. and this is my debug information.
> 
> > 2020-10-02 21:48:49,723 [ 362725]   WARN -                       WakaTime - Cannot run program "C:\Users\Hamid Reza\AppData\Roaming\WakaTime\wakatime-cli\wakatime-cli.exe": CreateProcess error=2, The system cannot find the file specified
> > java.io.IOException: Cannot run program "C:\Users\Hamid Reza\AppData\Roaming\WakaTime\wakatime-cli\wakatime-cli.exe": CreateProcess error=2, The system cannot find the file specified
> > at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
> > at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
> > at java.base/java.lang.Runtime.exec(Runtime.java:592)
> > at java.base/java.lang.Runtime.exec(Runtime.java:451)
> > at com.wakatime.intellij.plugin.WakaTime.sendHeartbeat(WakaTime.java:231)
> > at com.wakatime.intellij.plugin.WakaTime.processHeartbeatQueue(WakaTime.java:223)
> > at com.wakatime.intellij.plugin.WakaTime.access$100(WakaTime.java:46)
> > at com.wakatime.intellij.plugin.WakaTime$4.run(WakaTime.java:151)
> > at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
> > at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
> > at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
> > at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> > at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> > at java.base/java.lang.Thread.run(Thread.java:834)
> > Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
> > at java.base/java.lang.ProcessImpl.create(Native Method)
> > at java.base/java.lang.ProcessImpl.(ProcessImpl.java:478)
> > at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:154)
> > at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
> > ... 13 more

**Comment by alanhamlett** [comment] 2023-03-11 10:40
Closing since duplicate with #247.

**Closed by alanhamlett** 2023-03-11 10:40 UTC
Labels: question
