### ISSUE TITLE
wakaTime Not Working !!! but my api key  is true !!! 

### ISSUE THREAD

**Issue by itonedeveloper** [wakatime/jetbrains-wakatime#146] opened 2020-07-27 09:35 UTC
hi i have problem in wakatime !!!! 
WakaTime][ERROR] Invalid Api Key (104); Make sure your Api Key is correct!

wakaTime.log vsCode
`{"now": "2020/07/27 13:52:11 +0430", "version": "13.0.7", "plugin": "vscode/1.47.2 vscode-wakatime/4.0.0", "time": 1595841729.9006224, "caller": "wakatime/api.py", "lineno": 339, "is_write": true, "file": "/home/nerdpanda/web/php/mvc/index.php", "level": "WARNING", "message": "{'response_code': 401, 'response_content': '{\"error\":\"Unauthorized\"}\\n'}"}`

WakaTime.log PhpStorm

`{"now": "2020/07/27 13:06:42 +0430", "version": "13.0.7", "plugin": "PhpStorm/2020.1.4 PhpStorm-wakatime/11.0.1", "time": 1595838975.027, "caller": "wakatime/api.py", "lineno": 339, "is_write": true, "file": "/home/nerdpanda/web/php/mvc/index.php
![Screenshot_2020-07-27_13-58-41](https://user-images.githubusercontent.com/39291525/88527065-029c2e00-d012-11ea-8b0d-0f1ac8ed4286.png)
", "level": "WARNING", "message": "{'response_code': 401, 'response_content': '{\"error\":\"Unauthorized\"}\\n'}"}`

![Screenshot_2020-07-27_13-58-41](https://user-images.githubusercontent.com/39291525/88527212-38d9ad80-d012-11ea-818f-78e5562860cf.png)

**Comment by egordorichev** [comment] 2020-07-27 10:47
Looks like a global outage, have a look: 

* https://github.com/wakatime/vscode-wakatime/issues/143
* https://github.com/wakatime/wakatime/issues/221

**Comment by igorskyflyer** [comment] 2020-07-27 13:52
I can confirm having the same issue in (regular) VS Code since today, checked everything, my API key is correct.

**Comment by alanhamlett** [comment] 2020-07-27 14:38
Sorry, this was me. 😭 I broke the api key parsing, but it's fixed now. The plugin saves your stats and syncs them up the next time the plugin runs (the next time you're typing) so nothing is lost, but still sorry about the frustration it may have caused.

**Closed by alanhamlett** 2020-07-27 14:38 UTC
