### ISSUE TITLE
Factory is not registered as `com.intellij.statusBarWidgetFactory` extension

### ISSUE THREAD

**Issue by OndrejSpanel** [wakatime/jetbrains-wakatime#243] opened 2023-02-06 07:42 UTC
From my ide.log:

> 2023-02-06 08:36:10,290 [  80646]   WARN - #c.i.o.w.i.s.w.StatusBarWidgetsManager - Factory is not registered as `com.intellij.statusBarWidgetFactory` extension: WakaTime

This is with IntelliJ Ultimate EAP 2023.1, Build #IU-231.5920.14, built on January 27, 2023

**Comment by alanhamlett** [comment] 2023-02-06 12:12
I'm not able to reproduce this using:

```
IntelliJ IDEA 2023.1 EAP (Community Edition)
Build #IC-231.6471.13, built on February 3, 2023
```

Is this crashing your IDE or just a warning? Are you able to get a traceback from your `idea.log` for that warning or is it just that one line in your logs?

**Comment by OndrejSpanel** [comment] 2023-02-06 12:14
Just a warning. There is no callstack, just this single line.

**Comment by alanhamlett** [comment] 2023-02-06 12:56
Can you update to v14.1.4 which should print the traceback to your idea.log file?

**Comment by OndrejSpanel** [comment] 2023-02-09 07:50
I am not sure what traceback am I supposed to see. This is what I see with 14,1.4 update:

```
2023-02-09 08:47:11,546 [   2642]   WARN - #c.i.o.w.i.s.w.StatusBarWidgetsManager - org.jetbrains.plugins.scala.components.TypeAwareWidgetFactory doesn't define id for extension (point=com.intellij.statusBarWidgetFactory). Please specify `id` attribute.
2023-02-09 08:47:11,709 [   2805]   INFO - PerformancePlugin - Performance Plugin is in silent mode
```

**Comment by alanhamlett** [comment] 2023-02-09 11:23
Let's close this issue for now and if it happens again re-open it with the full traceback and then I'll have the necessary info for a fix.

**Closed by alanhamlett** 2023-02-09 11:23 UTC
