### ISSUE TITLE
WakaTime won't show up in WebStorm 2019.3.2

### ISSUE THREAD

**Issue by DAmNRelentless** [wakatime/jetbrains-wakatime#129] opened 2020-02-08 20:37 UTC
I installed WakaTime in my WebStorm 2019.3.2 since I liked using it on Visual Studio Code where it worked flawlessly.
It installed just fine but when I restarted the application, I wasn't asked for the API key.

I then navigated to my preferences > tools but waka is not listed there and even if I search for waka in the preferences, there is no entry. I reinstalled it multiple times but it doesn't seem to work.

**Comment by Tysiachnyi** [comment] 2020-02-16 21:03
did u fix it? i have this trouble 2
Re-install didn't help me

**Comment by DAmNRelentless** [comment] 2020-02-16 21:08
Nope. No response from the repository maintainers either so it seems to be abondoned.

**Comment by alanhamlett** [comment] 2020-02-16 23:49
It might be related to #131. Since the settings menu is missing from WebStorm it's most likely a compatibility issue in the plugin. If you could check that the plugin still works  in VS Code on the same machine, and also look for any error messages in your `idea.log` file that could help us fix the issue that would speed things up.

Here's how to locate your `idea.log` file:
https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files

**Comment by alanhamlett** [comment] 2020-02-17 03:13
Duplicate of #130.

**Comment by alanhamlett** [comment] 2020-02-17 03:16
We're working on updating the plugin for latest Jetbrains platform.

**Comment by DAmNRelentless** [comment] 2020-02-17 03:16
It's not a duplicate. My issue is about the plugin not properly installing or something like that. It doesn't show up in the plugin list where I could configure it to provide my API key.
This dude's issue is about the plugin not tracking his time properly when opening a project manually.

Also, as I mentioned in the issue already, the plugin works just fine in Visual Studio Code and I am still using it there. It only has this error in WebStorm for me. I can't talk about IntelliJ as I don't use it. Sadly, I can't provide any log files anymore since I uninstalled WebStorm since it didn't really fit my personal preference. Maybe @Tysiachnyi could provide a config to get you informed about the error.

**Comment by alanhamlett** [comment] 2020-02-17 04:23
Can you check if v9.3.4 works?

**Comment by Tysiachnyi** [comment] 2020-02-17 08:11
After update, i still don't have API input

**Comment by alanhamlett** [comment] 2020-02-17 16:58
@Tysiachnyi do you have an error message in your `idea.log` or `~/.wakatime.log` files?

**Comment by jvelezpo** [comment] 2020-02-17 22:31
hello @Tysiachnyi i try to install wakatime plugin on webstorm 2019.3 and it works 👌 

> After update, i still don't have API input

for you to see the input follow this steps 👇 


![image](https://user-images.githubusercontent.com/1050904/74689915-0007f380-51ab-11ea-9547-3e421cd951bf.png)
![image](https://user-images.githubusercontent.com/1050904/74689929-1910a480-51ab-11ea-9b3f-66b0e15b9df2.png)


and how did i installed the plugin?
it was installed here:
![image](https://user-images.githubusercontent.com/1050904/74689955-2cbc0b00-51ab-11ea-90e0-592b8487627c.png)

**Comment by Tysiachnyi** [comment] 2020-02-18 19:13
> hello @Tysiachnyi i try to install wakatime plugin on webstorm 2019.3 and it works 👌
> 
> > After update, i still don't have API input
> 
> for you to see the input follow this steps 👇
> 
> ![image](https://user-images.githubusercontent.com/1050904/74689915-0007f380-51ab-11ea-9547-3e421cd951bf.png)
> ![image](https://user-images.githubusercontent.com/1050904/74689929-1910a480-51ab-11ea-9b3f-66b0e15b9df2.png)
> 
> and how did i installed the plugin?
> it was installed here:
> ![image](https://user-images.githubusercontent.com/1050904/74689955-2cbc0b00-51ab-11ea-90e0-592b8487627c.png)

@jvelezpo thank you! it's help me)

**Closed** 2020-02-18 23:37 UTC
Labels: bug
