### ISSUE TITLE
PhpStorm Plugin: Crash upon start

### ISSUE THREAD

**Issue by cientistamaluco** [wakatime/jetbrains-wakatime#37] opened 2015-05-19 13:21 UTC
#### What steps will reproduce the problem?
1. Install Wakatime plugin
2. Restart PhpStorm
3. Exception occurs, PhpStorm is unable to start.

#### What is the expected result?
PhpStorm opens normally and Wakatime plugin works as expected

#### What happens instead?
Internal error occurs (java.lang.IllegalArgumentException)

#### Additional Info
Was only able to start PhpStorm after deleting ~/.WebIde80/config/plugins/WakaTime.jar and ~/.WebIde80/config/plugins/WakaTime-resources

#### PhpStorm log:
```
2015-05-19 10:57:50,635 [      0]   INFO -        #com.intellij.idea.Main - ------------------------------------------------------ IDE STARTED ------------------------------------------------------
2015-05-19 10:57:50,645 [     10]   INFO -        #com.intellij.idea.Main - IDE: PhpStorm (build #PS-139.1348, 12 Feb 2015 00:00)
2015-05-19 10:57:50,646 [     11]   INFO -        #com.intellij.idea.Main - OS: Linux (3.13.0-52-generic, amd64)
2015-05-19 10:57:50,646 [     11]   INFO -        #com.intellij.idea.Main - JRE: 1.7.0_80-b15 (Oracle Corporation)
2015-05-19 10:57:50,646 [     11]   INFO -        #com.intellij.idea.Main - JVM: 24.80-b11 (Java HotSpot(TM) 64-Bit Server VM)
2015-05-19 10:57:50,647 [     12]   INFO -        #com.intellij.idea.Main - JVM Args: -Xms128m -Xmx2048m -XX:MaxPermSize=350m -XX:ReservedCodeCacheSize=225m -ea -Dsun.io.useCanonCaches=false -Djava.net.preferIPv4Stack=true -Djsse.enableSNIExtension=false -XX:+UseConcMarkSweepGC -XX:SoftRefLRUPolicyMSPerMB=50 -Dawt.useSystemAAFontSettings=lcd -Djb.vmOptionsFile=/opt/phpstorm/bin/phpstorm64.vmoptions -XX:ErrorFile=/home/snogueira/java_error_in_WEBIDE_%p.log -Xbootclasspath/a:/opt/phpstorm/bin/../lib/boot.jar -Didea.paths.selector=WebIde80 -Didea.platform.prefix=PhpStorm -Didea.no.jre.check=true -Djb.restart.code=88
2015-05-19 10:57:50,665 [     30]   INFO -        #com.intellij.idea.Main - JNA library loaded (64-bit) in 18 ms
2015-05-19 10:57:50,832 [    197]   INFO - .intellij.idea.IdeaApplication - WM detected: Compiz
2015-05-19 10:57:51,404 [    769]   INFO - llij.ide.plugins.PluginManager - Cannot find optional descriptor uml-java-support.xml
2015-05-19 10:57:51,417 [    782]   INFO - llij.ide.plugins.PluginManager - Cannot find optional descriptor uml-properties-support.xml
2015-05-19 10:57:52,406 [   1771]   INFO - llij.ide.plugins.PluginManager - 56 plugins initialized in 1379 ms
2015-05-19 10:57:52,407 [   1772]   INFO - llij.ide.plugins.PluginManager - Loaded bundled plugins: ASP (0.1), Apache config (.htaccess) support (139.1348), Behat Support (139.1348), Blade Support (139.1348), CSS Support, CVS Integration (11), CoffeeScript (2.0), Command Line Tool Support (139.1348), Database Tools and SQL (1.0), Drupal Support (139.1348), File Watchers (139.1348), Framework MVC Structure Support (139.1348), GNU GetText files support (*.po) (136.SNAPSHOT), Gherkin (999.999), Git Integration (8.1), GitHub, Google App Engine Support for PHP (139.1348), HAML, HTML Tools (2.0), IDEA CORE, Ini4Idea (139.1348), IntelliLang (8.0), Java Server Pages Integration (1.0), JavaScript Debugger (1.0), JavaScript Intention Power Pack (0.9.4), JavaScript Support (1.0), LESS support, PHP (139.1348), PHP Remote Interpreter (139.1348), Perforce Integration (2.0), Phing Support (139.1348), QuirksMode, REST Client, ReStructuredText Support (136.SNAPSHOT), Refactor-X (2.01), Remote Hosts Access (0.1), SASS support, SSH Remote Run (0.1), Subversion Integration (1.1), Task Management (1.0), Terminal (0.1), TextMate bundles support (VERSION), Twig Support (139.1348), UML Support (1.0), Vagrant (139.1348), W3C Validators (2.0), WordPress Support (139.1348), XPathView + XSLT Support (4), XSLT-Debugger (1.4), YAML, hg4idea (10.0)
2015-05-19 10:57:52,407 [   1772]   INFO - llij.ide.plugins.PluginManager - Loaded custom plugins: .ignore (1.1.2), BashSupport (1.4.0_build139), Bitbucket (1.2.3-SNAPSHOT), Markdown (0.9.7), WakaTime (4.0.10)
2015-05-19 10:57:52,962 [   2327]   INFO - ellij.util.io.PagedFileStorage - lower=100; upper=200; buffer=10; max=2091646976
2015-05-19 10:57:53,042 [   2407]   INFO - api.vfs.impl.local.FileWatcher - Starting file watcher: /opt/phpstorm/bin/fsnotifier64
2015-05-19 10:57:53,050 [   2415]   INFO - api.vfs.impl.local.FileWatcher - Native file watcher is operational.
2015-05-19 10:57:54,339 [   3704]   INFO - lij.diagnostic.DebugLogManager - Set DEBUG for the following categories: []
2015-05-19 10:57:55,222 [   4587]   INFO -                       WakaTime - Initializing WakaTime plugin v4.0.10 (https://wakatime.com/)
2015-05-19 10:57:55,225 [   4590]   INFO -                       WakaTime - Downloading and installing wakatime-cli ...
2015-05-19 10:57:55,896 [   5261]   INFO - ellij.project.impl.ProjectImpl - 20 project components initialized in 638 ms
2015-05-19 10:57:55,897 [   5262]   INFO - le.impl.ModuleManagerComponent - 0 module(s) loaded in 0 ms
2015-05-19 10:57:56,239 [   5604]  ERROR - llij.ide.plugins.PluginManager - null
java.lang.IllegalArgumentException
	at java.util.concurrent.ScheduledThreadPoolExecutor.scheduleWithFixedDelay(ScheduledThreadPoolExecutor.java:586)
	at com.intellij.ide.a.g.q.c(q.java:406)
	at com.intellij.ide.a.g.q.t(q.java:539)
	at com.intellij.ide.a.g.bb$3$0.run(bb$3$0.java:396)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:364)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:154)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:182)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:221)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:219)
	at java.awt.Dialog.show(Dialog.java:1082)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:779)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:464)
	at com.intellij.openapi.ui.DialogWrapper.showAndGetOk(DialogWrapper.java:1569)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1536)
	at com.wakatime.intellij.plugin.ApiKey.promptForApiKey(ApiKey.java:61)
	at com.wakatime.intellij.plugin.WakaTime.initComponent(WakaTime.java:97)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter$1.getComponentInstance(ComponentManagerImpl.java:567)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:609)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:236)
	at com.intellij.util.pico.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:223)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:210)
	at org.picocontainer.alternatives.AbstractDelegatingMutablePicoContainer.getComponentInstance(AbstractDelegatingMutablePicoContainer.java:75)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponent(ComponentManagerImpl.java:124)
	at com.intellij.openapi.application.impl.ApplicationImpl.createComponent(ApplicationImpl.java:358)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:115)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:86)
	at com.intellij.openapi.components.impl.stores.ApplicationStoreImpl.load(ApplicationStoreImpl.java:110)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:511)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:493)
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:158)
	at com.intellij.idea.MainImpl$1$1$1.run(MainImpl.java:66)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:364)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
2015-05-19 10:57:56,244 [   5609]  ERROR - llij.ide.plugins.PluginManager - PhpStorm 8.0.3  Build #PS-139.1348
2015-05-19 10:57:56,244 [   5609]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.7.0_80
2015-05-19 10:57:56,244 [   5609]  ERROR - llij.ide.plugins.PluginManager - VM: Java HotSpot(TM) 64-Bit Server VM
2015-05-19 10:57:56,245 [   5610]  ERROR - llij.ide.plugins.PluginManager - Vendor: Oracle Corporation
2015-05-19 10:57:56,245 [   5610]  ERROR - llij.ide.plugins.PluginManager - OS: Linux
2015-05-19 10:57:57,895 [   7260]   INFO -                       WakaTime - Finished downloading and installing wakatime-cli.
2015-05-19 11:03:35,178 [ 344543]   INFO -        #com.intellij.idea.Main - ------------------------------------------------------ IDE SHUTDOWN ------------------------------------------------------
2015-05-19 11:03:35,197 [ 344562]   INFO - il.indexing.FileBasedIndexImpl - START INDEX SHUTDOWN 
```

**Comment by alanhamlett** [comment] 2015-05-19 19:17
I'm not able to reproduce this on Mac OS X, but I'll try on Linux later.

**Comment by junxy** [comment] 2015-06-02 02:12
Hi, I use phpStorm, Stopped at the startup screen  on Mac OS X, Yesterday is working, Server is down?

**Comment by alanhamlett** [comment] 2015-08-04 00:10
Closing as fixed in latest version.

**Closed by alanhamlett** 2015-08-04 00:10 UTC
