### ISSUE TITLE
Doesn't work in IntelliJ 2022.1.2

### ISSUE THREAD

**Issue by ViiictorXD** [wakatime/jetbrains-wakatime#225] opened 2022-06-21 00:24 UTC
I installed the WakaTime plugin in IntelliJ, when I restart the IDE, it doesn't ask me to put the API key, I already tried to create the file manually putting the API key and it still didn't work.

**Comment by alanhamlett** [comment] 2022-06-21 02:17
Possible duplicate of #223.

1. Do you have a `Tools -> WakaTime Settings` menu inside your IntelliJ?
2. Are there any errors related to WakaTime in your `idea.log` file?
3. Are there any recent errors in your `~/.wakatime.log` file?

**Comment by alanhamlett** [comment] 2022-06-21 06:24
@besscroft that looks like a proxy error. Did you mean to use `https://localhost:7890` instead of `http`?

Also check out [this recent comment](https://github.com/wakatime/jetbrains-wakatime/issues/224#issuecomment-1159546371).

**Comment by besscroft** [comment] 2022-06-22 01:45
@alanhamlett 
Thank you for your reply!
I cleared proxy settings, the common proxy configuration I use in idea and vscode, vacode works normally, idea does not work, I think there may be other reasons.

**Comment by alanhamlett** [comment] 2022-06-22 01:55
IntelliJ can detect a proxy from the IntelliJ settings and also from `~/.wakatime.cfg`, while vscode only uses `~/.wakatime.cfg`. Maybe your IntelliJ still has a proxy configured. Try excluding `*wakatime.com` from your IntelliJ proxy settings?

**Comment by besscroft** [comment] 2022-06-22 01:57
Thank you for your reply!
I double checked and cleared the proxy.

**Comment by besscroft** [comment] 2022-06-23 01:15
![image](https://user-images.githubusercontent.com/33775809/175186548-ea474941-769a-434c-9409-0cbf1664da6e.png)
Thank you for your reply, it's working fine now.

**Closed** 2022-06-23 01:53 UTC

**Comment by bushiyi** [comment] 2022-10-09 09:57
this solved my problem
